services:
  api:
    container_name: saas_agendamentos_api
    build: .
    restart: always
    ports:
      - "3333:3000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - saas-net

  db:
    container_name: saas_agendamentos_db
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=l9uxngsctIZ2zPygQTqAHzhIhOq89yUB
      - POSTGRES_DB=saas_agendamentos
    volumes:
      - saas_db_data:/var/lib/postgresql/data
    networks:
      - saas-net
    ports:
      - "5432:5432"

volumes:
  saas_db_data:

networks:
  saas-net:
    driver: bridge